package service

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/futurebuildai/buildos/internal/models"
	"github.com/futurebuildai/buildos/internal/store"
)

// Setup-specific sentinel errors. Handlers map to HTTP codes:
//
//	ErrSetupAlreadyComplete → 409 SETUP_ALREADY_COMPLETE
//	ErrInvalidBootstrapToken → 401 INVALID_BOOTSTRAP_TOKEN
//	ErrBootstrapTokenExpired → 401 BOOTSTRAP_TOKEN_EXPIRED (same code as invalid for security)
//
// Reuses ErrNotFound, ErrInvalidInput from budget.go (same package).
var (
	ErrSetupAlreadyComplete        = errors.New("setup: onboarding already complete")
	ErrInvalidBootstrapToken       = errors.New("setup: invalid bootstrap token")
	ErrBootstrapUserNotProvisioned = errors.New("setup: bootstrap redeemer not yet provisioned in users table")
)

// Setup audit-log resource type / action constants. Wizard rows are
// not first-class business objects, so the resource_type uses the
// org_id (single subject per wizard run) and the action namespace
// captures which step landed. Lets `/audit?action_prefix=setup.`
// reconstruct the full wizard flow per org.
const (
	AuditResourceOrganization = "organization"

	AuditActionSetupCompanyInfo    = "setup.company_info.updated"
	AuditActionSetupTrade          = "setup.trade.created"
	AuditActionSetupCostCode       = "setup.cost_code.created"
	AuditActionSetupCalendar       = "setup.calendar.created"
	AuditActionSetupHoliday        = "setup.holiday.created"
	AuditActionSetupJurisdiction   = "setup.jurisdiction.created"
	AuditActionSetupCompleted      = "setup.completed"
	AuditActionSetupBootstrapIssue = "setup.bootstrap_token.issued"
	AuditActionSetupBootstrapClaim = "setup.bootstrap_token.redeemed"
)

// bootstrapTokenByteLen is the cleartext length for a newly-issued
// bootstrap token. 32 bytes (256 bits) from crypto/rand puts the
// cleartext well beyond any feasible brute-force budget even against
// a deterministic (sha256) hash — the security comes from the
// entropy of the input, not the cost of the hash.
const bootstrapTokenByteLen = 32

// DefaultBootstrapTokenTTL is the default lifetime applied when
// IssueBootstrapToken is called without an explicit expiry. Short
// enough that a leaked token in a fork-init artifact loses value
// before an attacker can discover the fork's URL and Brain JWKS;
// long enough that a slow first-admin claim doesn't have to race
// the clock.
const DefaultBootstrapTokenTTL = 7 * 24 * time.Hour

// SetupService orchestrates the embedded onboarding wizard (MB-7).
// One wizard run per fork — every method is scoped by org_id and the
// service uses the same single tx-per-mutation pattern as the other
// service-layer types (audit + write commit together).
//
// Bootstrap-token note: the cleartext token is generated by
// IssueBootstrapToken and shown ONCE to the caller (cmd/buildos-fork-init
// in W2 / operator scripts in W3+). Only the sha256 hash lands in
// setup_bootstrap_tokens. A 256-bit random cleartext makes the
// preimage space large enough that no offline crack is possible
// against a deterministic hash, and the deterministic hash is what
// lets the redemption path do a direct unique-index lookup. argon2id
// would force a full table scan on redemption with no security gain.
type SetupService struct {
	pool  *pgxpool.Pool
	store *store.SetupStore
	audit AuditRecorder
	now   func() time.Time
}

// NewSetupService creates a setup service bound to a pool + store.
// audit may be nil; nil falls back to a no-op recorder. clock may be
// nil; nil uses time.Now (tests inject a deterministic clock).
func NewSetupService(pool *pgxpool.Pool, s *store.SetupStore, audit AuditRecorder, clock func() time.Time) *SetupService {
	if audit == nil {
		audit = NewNoopAuditRecorder()
	}
	if clock == nil {
		clock = time.Now
	}
	return &SetupService{pool: pool, store: s, audit: audit, now: clock}
}

// ---------- State (wizard read) ----------

// SetupState is the GET /setup/state response shape. Each section is
// either nil (step not done) or populated. The wizard UI uses the
// presence/absence of each section to decide which step to land on.
type SetupState struct {
	OrgID               uuid.UUID
	OnboardingComplete  bool
	CompanyProfile      models.CompanyProfile
	Trades              []models.TradeCategory
	CostCodes           []models.CostCode
	DefaultCalendar     *models.WorkingCalendar
	DefaultHolidays     []models.HolidayOverride
	PermitJurisdictions []models.PermitJurisdiction
}

// GetState returns a consistent snapshot of the wizard's progress.
// Reads under a single read-only tx so partial-progress states are
// internally consistent (wizard UI never sees half a step).
func (s *SetupService) GetState(ctx context.Context, orgID uuid.UUID) (SetupState, error) {
	if orgID == uuid.Nil {
		return SetupState{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	var out SetupState
	out.OrgID = orgID
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{AccessMode: pgx.ReadOnly}, func(tx pgx.Tx) error {
		cp, err := s.store.GetCompanyProfile(ctx, tx, orgID)
		if err != nil {
			return err
		}
		out.CompanyProfile = cp
		out.OnboardingComplete = cp.OnboardingComplete

		trades, err := s.store.ListTradeCategories(ctx, tx, orgID)
		if err != nil {
			return err
		}
		out.Trades = trades

		costs, err := s.store.ListCostCodes(ctx, tx, orgID)
		if err != nil {
			return err
		}
		out.CostCodes = costs

		cal, err := s.store.GetDefaultWorkingCalendar(ctx, tx, orgID)
		if err == nil {
			out.DefaultCalendar = &cal
			hols, herr := s.store.ListHolidaysForCalendar(ctx, tx, cal.ID)
			if herr != nil {
				return herr
			}
			out.DefaultHolidays = hols
		} else if !errors.Is(err, store.ErrNotFound) {
			return err
		}

		juris, err := s.store.ListPermitJurisdictions(ctx, tx, orgID)
		if err != nil {
			return err
		}
		out.PermitJurisdictions = juris
		return nil
	})
	if err != nil {
		return SetupState{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 1: Company info ----------

// UpdateCompanyInfoInput is the wizard step-1 payload. Fields are
// pointers so the caller can patch a subset without clobbering prior
// submissions.
type UpdateCompanyInfoInput struct {
	OrgID       uuid.UUID
	UserSub     string
	LegalName   *string
	Address     *string
	EIN         *string
	CompanyType *string
	Region      *string
}

// UpdateCompanyInfo writes the company-profile fields. The audit row
// records the patch (only fields the caller submitted) so the wizard
// trail shows step-by-step diffs rather than the full snapshot.
func (s *SetupService) UpdateCompanyInfo(ctx context.Context, in UpdateCompanyInfoInput) (models.CompanyProfile, error) {
	if in.OrgID == uuid.Nil {
		return models.CompanyProfile{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if !atLeastOneNonNil(in.LegalName, in.Address, in.EIN, in.CompanyType, in.Region) {
		return models.CompanyProfile{}, fmt.Errorf("%w: at least one field required", ErrInvalidInput)
	}
	if in.Region != nil && !looksLikeRegion(*in.Region) {
		return models.CompanyProfile{}, fmt.Errorf("%w: region must look like ISO-3166-2 (e.g. US-CT)", ErrInvalidInput)
	}

	var out models.CompanyProfile
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		if err := s.store.UpdateCompanyProfile(ctx, tx, store.UpdateCompanyProfileParams{
			OrgID:       in.OrgID,
			LegalName:   in.LegalName,
			Address:     in.Address,
			EIN:         in.EIN,
			CompanyType: in.CompanyType,
			Region:      in.Region,
		}); err != nil {
			return err
		}
		cp, err := s.store.GetCompanyProfile(ctx, tx, in.OrgID)
		if err != nil {
			return err
		}
		out = cp

		patch, _ := json.Marshal(map[string]any{
			"legal_name":   in.LegalName,
			"address":      in.Address,
			"ein":          in.EIN,
			"company_type": in.CompanyType,
			"region":       in.Region,
		})
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupCompanyInfo,
			ResourceType: AuditResourceOrganization,
			ResourceID:   in.OrgID,
			After:        patch,
		})
		return nil
	})
	if err != nil {
		return models.CompanyProfile{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 3: Trades ----------

// CreateTradeInput is the wizard step-3 single-trade payload. Step 3
// is bulk-friendly (the wizard typically submits an array); the
// service exposes the single-row method so per-row failures (e.g.
// UNIQUE collision on code) surface individually.
type CreateTradeInput struct {
	OrgID       uuid.UUID
	UserSub     string
	Code        string
	Name        string
	Description *string
	IsDefault   bool
}

// CreateTrade inserts a trade category. Code is normalized (upper +
// trimmed) so the operator can paste "  elec " and land "ELEC". Codes
// are required to be 1..16 ASCII chars after normalization.
func (s *SetupService) CreateTrade(ctx context.Context, in CreateTradeInput) (models.TradeCategory, error) {
	in.Code = strings.ToUpper(strings.TrimSpace(in.Code))
	in.Name = strings.TrimSpace(in.Name)
	if in.OrgID == uuid.Nil {
		return models.TradeCategory{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if !isShortCode(in.Code, 1, 16) {
		return models.TradeCategory{}, fmt.Errorf("%w: code must be 1..16 ASCII chars (A-Z, 0-9, _, -)", ErrInvalidInput)
	}
	if in.Name == "" {
		return models.TradeCategory{}, fmt.Errorf("%w: name required", ErrInvalidInput)
	}

	var out models.TradeCategory
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		t, err := s.store.CreateTradeCategory(ctx, tx, store.CreateTradeCategoryParams{
			OrgID:       in.OrgID,
			Code:        in.Code,
			Name:        in.Name,
			Description: in.Description,
			IsDefault:   in.IsDefault,
		})
		if err != nil {
			return err
		}
		out = t
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupTrade,
			ResourceType: AuditResourceOrganization,
			ResourceID:   t.ID,
		})
		return nil
	})
	if err != nil {
		return models.TradeCategory{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 4: Cost codes ----------

// CreateCostCodeInput is the wizard step-4 single-code payload.
type CreateCostCodeInput struct {
	OrgID      uuid.UUID
	UserSub    string
	Code       string
	Name       string
	Division   string
	ParentCode *string
	IsDefault  bool
}

// CreateCostCode inserts a cost code. Code is normalized (trimmed)
// and validated as MasterFormat-shaped (NN-NN-NN or shorter NN-NN
// for parents). Strictly enforcing the CSI shape catches typo-style
// errors at the wizard layer where they're cheap to fix.
func (s *SetupService) CreateCostCode(ctx context.Context, in CreateCostCodeInput) (models.CostCode, error) {
	in.Code = strings.TrimSpace(in.Code)
	in.Name = strings.TrimSpace(in.Name)
	in.Division = strings.TrimSpace(in.Division)
	if in.OrgID == uuid.Nil {
		return models.CostCode{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if !looksLikeCSICode(in.Code) {
		return models.CostCode{}, fmt.Errorf("%w: code must look like NN-NN-NN (CSI MasterFormat)", ErrInvalidInput)
	}
	if in.Name == "" {
		return models.CostCode{}, fmt.Errorf("%w: name required", ErrInvalidInput)
	}
	if in.Division == "" {
		return models.CostCode{}, fmt.Errorf("%w: division required", ErrInvalidInput)
	}

	var out models.CostCode
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		c, err := s.store.CreateCostCode(ctx, tx, store.CreateCostCodeParams{
			OrgID:      in.OrgID,
			Code:       in.Code,
			Name:       in.Name,
			Division:   in.Division,
			ParentCode: in.ParentCode,
			IsDefault:  in.IsDefault,
		})
		if err != nil {
			return err
		}
		out = c
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupCostCode,
			ResourceType: AuditResourceOrganization,
			ResourceID:   c.ID,
		})
		return nil
	})
	if err != nil {
		return models.CostCode{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 5: Working calendar ----------

// CreateCalendarInput is the wizard step-5 calendar payload. Holidays
// are submitted in the same step but inserted in a separate (atomic)
// call after the calendar row is created.
type CreateCalendarInput struct {
	OrgID            uuid.UUID
	UserSub          string
	Name             string
	Timezone         string
	WorkingDaysMask  int16
	DailyWorkMinutes int
	IsDefault        bool
}

// CreateCalendar inserts a working_calendars row. Timezone is
// validated as a real IANA TZ via time.LoadLocation — catches typos
// (e.g. "America/Hartford" vs "America/New_York") before the CPM
// engine fails to load it at recalc time.
func (s *SetupService) CreateCalendar(ctx context.Context, in CreateCalendarInput) (models.WorkingCalendar, error) {
	in.Name = strings.TrimSpace(in.Name)
	in.Timezone = strings.TrimSpace(in.Timezone)
	if in.OrgID == uuid.Nil {
		return models.WorkingCalendar{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if in.Name == "" {
		return models.WorkingCalendar{}, fmt.Errorf("%w: name required", ErrInvalidInput)
	}
	if in.Timezone == "" {
		in.Timezone = "America/New_York" // schema default
	}
	if _, err := time.LoadLocation(in.Timezone); err != nil {
		return models.WorkingCalendar{}, fmt.Errorf("%w: timezone %q is not a valid IANA TZ", ErrInvalidInput, in.Timezone)
	}
	if in.WorkingDaysMask < 0 || in.WorkingDaysMask > 127 {
		return models.WorkingCalendar{}, fmt.Errorf("%w: working_days_mask must be 0..127", ErrInvalidInput)
	}
	if in.WorkingDaysMask == 0 {
		in.WorkingDaysMask = models.WorkingDaysMonFri
	}
	if in.DailyWorkMinutes <= 0 {
		in.DailyWorkMinutes = 480
	}
	if in.DailyWorkMinutes > 1440 {
		return models.WorkingCalendar{}, fmt.Errorf("%w: daily_work_minutes must be 1..1440", ErrInvalidInput)
	}

	var out models.WorkingCalendar
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		c, err := s.store.CreateWorkingCalendar(ctx, tx, store.CreateWorkingCalendarParams{
			OrgID:            in.OrgID,
			Name:             in.Name,
			Timezone:         in.Timezone,
			WorkingDaysMask:  in.WorkingDaysMask,
			DailyWorkMinutes: in.DailyWorkMinutes,
			IsDefault:        in.IsDefault,
		})
		if err != nil {
			return err
		}
		out = c
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupCalendar,
			ResourceType: AuditResourceOrganization,
			ResourceID:   c.ID,
		})
		return nil
	})
	if err != nil {
		return models.WorkingCalendar{}, mapSetupStoreError(err)
	}
	return out, nil
}

// AddHolidayInput is the per-holiday payload. Multiple holidays go in
// separate AddHoliday calls so per-row UNIQUE collisions are diagnosed
// individually.
type AddHolidayInput struct {
	OrgID       uuid.UUID
	UserSub     string
	CalendarID  uuid.UUID
	HolidayDate time.Time
	Name        string
}

// AddHoliday inserts a holiday override. HolidayDate is truncated to
// UTC midnight before insert (schema column is DATE; truncating here
// keeps the audit-log row aligned with what landed in DB).
func (s *SetupService) AddHoliday(ctx context.Context, in AddHolidayInput) (models.HolidayOverride, error) {
	in.Name = strings.TrimSpace(in.Name)
	if in.OrgID == uuid.Nil || in.CalendarID == uuid.Nil {
		return models.HolidayOverride{}, fmt.Errorf("%w: org_id and calendar_id required", ErrInvalidInput)
	}
	if in.Name == "" {
		return models.HolidayOverride{}, fmt.Errorf("%w: name required", ErrInvalidInput)
	}
	if in.HolidayDate.IsZero() {
		return models.HolidayOverride{}, fmt.Errorf("%w: holiday_date required", ErrInvalidInput)
	}
	// Truncate to UTC midnight — DATE columns store calendar days.
	in.HolidayDate = time.Date(in.HolidayDate.Year(), in.HolidayDate.Month(), in.HolidayDate.Day(), 0, 0, 0, 0, time.UTC)

	var out models.HolidayOverride
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		h, err := s.store.CreateHolidayOverride(ctx, tx, store.CreateHolidayOverrideParams{
			CalendarID:  in.CalendarID,
			OrgID:       in.OrgID,
			HolidayDate: in.HolidayDate,
			Name:        in.Name,
		})
		if err != nil {
			return err
		}
		out = h
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupHoliday,
			ResourceType: AuditResourceOrganization,
			ResourceID:   h.ID,
		})
		return nil
	})
	if err != nil {
		return models.HolidayOverride{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 6: Permit jurisdictions ----------

// AddJurisdictionInput is the wizard step-6 payload. PermitTypes and
// InspectionChecklist are raw JSONB; the caller is expected to pass
// well-formed JSON bytes (the HTTP handler in W3 will re-marshal from
// the wire schema).
type AddJurisdictionInput struct {
	OrgID               uuid.UUID
	UserSub             string
	Name                string
	Region              *string
	PermitTypes         []byte
	InspectionChecklist []byte
	Notes               *string
}

// AddJurisdiction inserts a permit_jurisdictions row. Empty / nil
// PermitTypes and InspectionChecklist fall back to '[]' in the store.
func (s *SetupService) AddJurisdiction(ctx context.Context, in AddJurisdictionInput) (models.PermitJurisdiction, error) {
	in.Name = strings.TrimSpace(in.Name)
	if in.OrgID == uuid.Nil {
		return models.PermitJurisdiction{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if in.Name == "" {
		return models.PermitJurisdiction{}, fmt.Errorf("%w: name required", ErrInvalidInput)
	}
	if len(in.PermitTypes) > 0 && !json.Valid(in.PermitTypes) {
		return models.PermitJurisdiction{}, fmt.Errorf("%w: permit_types must be valid JSON", ErrInvalidInput)
	}
	if len(in.InspectionChecklist) > 0 && !json.Valid(in.InspectionChecklist) {
		return models.PermitJurisdiction{}, fmt.Errorf("%w: inspection_checklist must be valid JSON", ErrInvalidInput)
	}

	var out models.PermitJurisdiction
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		if err := s.guardNotComplete(ctx, tx, in.OrgID); err != nil {
			return err
		}
		j, err := s.store.CreatePermitJurisdiction(ctx, tx, store.CreatePermitJurisdictionParams{
			OrgID:               in.OrgID,
			Name:                in.Name,
			Region:              in.Region,
			PermitTypes:         in.PermitTypes,
			InspectionChecklist: in.InspectionChecklist,
			Notes:               in.Notes,
		})
		if err != nil {
			return err
		}
		out = j
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupJurisdiction,
			ResourceType: AuditResourceOrganization,
			ResourceID:   j.ID,
		})
		return nil
	})
	if err != nil {
		return models.PermitJurisdiction{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Step 8: Complete ----------

// CompleteSetupInput is the final-step payload. Idempotent: a repeat
// call returns the same completed-at, no error.
type CompleteSetupInput struct {
	OrgID   uuid.UUID
	UserSub string
}

// Complete flips onboarding_complete=true after verifying the minimum
// preconditions are met: company profile filled, at least one trade,
// at least one cost code, and a default working calendar. The HTTP
// handler in W3 surfaces missing-prereq errors as 422 SETUP_INCOMPLETE.
func (s *SetupService) Complete(ctx context.Context, in CompleteSetupInput) (models.CompanyProfile, error) {
	if in.OrgID == uuid.Nil {
		return models.CompanyProfile{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}

	var out models.CompanyProfile
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		cp, err := s.store.GetCompanyProfile(ctx, tx, in.OrgID)
		if err != nil {
			return err
		}
		if cp.OnboardingComplete {
			// Idempotent: return the existing snapshot. No audit row
			// on a no-op to keep the trail clean.
			out = cp
			return nil
		}
		if cp.LegalName == nil || *cp.LegalName == "" {
			return fmt.Errorf("%w: company info incomplete (legal_name missing)", ErrInvalidInput)
		}
		trades, err := s.store.ListTradeCategories(ctx, tx, in.OrgID)
		if err != nil {
			return err
		}
		if len(trades) == 0 {
			return fmt.Errorf("%w: at least one trade required", ErrInvalidInput)
		}
		codes, err := s.store.ListCostCodes(ctx, tx, in.OrgID)
		if err != nil {
			return err
		}
		if len(codes) == 0 {
			return fmt.Errorf("%w: at least one cost code required", ErrInvalidInput)
		}
		if _, err := s.store.GetDefaultWorkingCalendar(ctx, tx, in.OrgID); err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return fmt.Errorf("%w: a default working calendar is required", ErrInvalidInput)
			}
			return err
		}

		if err := s.store.CompleteOnboarding(ctx, tx, in.OrgID, s.now()); err != nil {
			return err
		}
		cp2, err := s.store.GetCompanyProfile(ctx, tx, in.OrgID)
		if err != nil {
			return err
		}
		out = cp2

		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        in.OrgID,
			UserSub:      in.UserSub,
			Action:       AuditActionSetupCompleted,
			ResourceType: AuditResourceOrganization,
			ResourceID:   in.OrgID,
		})
		return nil
	})
	if err != nil {
		return models.CompanyProfile{}, mapSetupStoreError(err)
	}
	return out, nil
}

// ---------- Bootstrap tokens ----------

// IssuedBootstrapToken is the result of IssueBootstrapToken — the
// caller MUST show Cleartext to the operator once and never again
// (e.g. write it into fork.yaml + a secret store). Only the hash
// landed in the DB.
type IssuedBootstrapToken struct {
	ID        uuid.UUID
	Cleartext string
	ExpiresAt time.Time
}

// IssueBootstrapToken mints a one-shot owner-claim token. The
// cleartext is 32 random bytes base64url-encoded (43 chars); the
// sha256 hash lands in setup_bootstrap_tokens. TTL=0 falls back to
// DefaultBootstrapTokenTTL.
//
// Idempotency: this method does NOT collapse against an existing
// active token — the caller is expected to use the same secret-store
// file (and skip the call entirely if it already exists). Re-issuing
// produces a second active token; the redemption path accepts either
// until one is consumed.
func (s *SetupService) IssueBootstrapToken(ctx context.Context, orgID uuid.UUID, userSub string, ttl time.Duration) (IssuedBootstrapToken, error) {
	if orgID == uuid.Nil {
		return IssuedBootstrapToken{}, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	if ttl <= 0 {
		ttl = DefaultBootstrapTokenTTL
	}

	cleartext, err := generateBootstrapTokenCleartext()
	if err != nil {
		return IssuedBootstrapToken{}, fmt.Errorf("generate bootstrap token: %w", err)
	}
	hash := hashBootstrapToken(cleartext)
	expires := s.now().Add(ttl)

	var id uuid.UUID
	err = pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		// Refuse to mint a bootstrap token for an org whose wizard
		// is already complete — the token would have no purpose and
		// just expand the attack surface.
		cp, gerr := s.store.GetCompanyProfile(ctx, tx, orgID)
		if gerr != nil {
			return gerr
		}
		if cp.OnboardingComplete {
			return ErrSetupAlreadyComplete
		}

		var qErr error
		id, qErr = s.store.CreateBootstrapToken(ctx, tx, store.CreateBootstrapTokenParams{
			OrgID:     orgID,
			TokenHash: hash,
			ExpiresAt: expires,
		})
		if qErr != nil {
			return qErr
		}
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        orgID,
			UserSub:      userSub,
			Action:       AuditActionSetupBootstrapIssue,
			ResourceType: AuditResourceOrganization,
			ResourceID:   id,
		})
		return nil
	})
	if err != nil {
		return IssuedBootstrapToken{}, mapSetupStoreError(err)
	}
	return IssuedBootstrapToken{ID: id, Cleartext: cleartext, ExpiresAt: expires}, nil
}

// RedeemedBootstrapToken is what RedeemBootstrapToken returns. The
// caller (HTTP handler in W3) uses OrgID to populate the request
// context for subsequent wizard calls in the same session.
type RedeemedBootstrapToken struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// RedeemBootstrapToken validates a cleartext token + marks it
// redeemed. redeemerSub is recorded in setup_bootstrap_tokens.redeemed_by
// after being parsed as a UUID (the HTTP handler passes the JWT sub
// once Brain emits UUID subs; for now nil-sub is accepted and the
// row records redeemed_by=NULL, but the consistency CHECK forbids
// that — so callers MUST pass a non-nil UUID).
//
// Returns ErrInvalidBootstrapToken on any failure (missing, expired,
// already redeemed, hash mismatch). The error is intentionally
// uniform — distinguishing reasons leaks information to an attacker
// probing the endpoint.
func (s *SetupService) RedeemBootstrapToken(ctx context.Context, cleartext string, redeemerID uuid.UUID) (RedeemedBootstrapToken, error) {
	if cleartext == "" {
		return RedeemedBootstrapToken{}, ErrInvalidBootstrapToken
	}
	if redeemerID == uuid.Nil {
		return RedeemedBootstrapToken{}, fmt.Errorf("%w: redeemer required", ErrInvalidInput)
	}
	hash := hashBootstrapToken(cleartext)
	now := s.now()

	var out RedeemedBootstrapToken
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		tok, err := s.store.GetActiveBootstrapTokenByHash(ctx, tx, hash, now)
		if err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return ErrInvalidBootstrapToken
			}
			return err
		}
		if err := s.store.RedeemBootstrapToken(ctx, tx, tok.ID, redeemerID, now); err != nil {
			if errors.Is(err, store.ErrNotFound) {
				// Lost a race against a concurrent redeem.
				return ErrInvalidBootstrapToken
			}
			return err
		}
		out = RedeemedBootstrapToken{ID: tok.ID, OrgID: tok.OrgID}
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        tok.OrgID,
			Action:       AuditActionSetupBootstrapClaim,
			ResourceType: AuditResourceOrganization,
			ResourceID:   tok.ID,
		})
		return nil
	})
	if err != nil {
		return RedeemedBootstrapToken{}, mapSetupStoreError(err)
	}
	return out, nil
}

// RedeemBootstrapTokenForSubject is the HTTP-facing wrapper around
// RedeemBootstrapToken. It resolves the caller's OIDC subject to a
// users.id via SetupStore.LookupUserIDBySubject, verifies the token
// belongs to the caller's org (so a cross-org user cannot burn another
// org's token), then redeems atomically.
//
// Failure semantics (matching the HTTP error mapping in W3):
//   - subject not in users          → ErrBootstrapUserNotProvisioned (412)
//   - token not found / expired     → ErrInvalidBootstrapToken (401)
//   - token belongs to a different org than the JWT claim
//     → ErrInvalidBootstrapToken (401; NOT consumed)
//   - any redeem-time race          → ErrInvalidBootstrapToken (401)
//
// callerOrgID must be the org_id claim on the redeemer's JWT — used
// for both the user-lookup scope and the cross-org safety check.
func (s *SetupService) RedeemBootstrapTokenForSubject(ctx context.Context, cleartext, subject string, callerOrgID uuid.UUID) (RedeemedBootstrapToken, error) {
	if cleartext == "" {
		return RedeemedBootstrapToken{}, ErrInvalidBootstrapToken
	}
	if callerOrgID == uuid.Nil {
		return RedeemedBootstrapToken{}, fmt.Errorf("%w: caller org_id required", ErrInvalidInput)
	}
	if subject == "" {
		return RedeemedBootstrapToken{}, fmt.Errorf("%w: subject required", ErrInvalidInput)
	}
	hash := hashBootstrapToken(cleartext)
	now := s.now()

	var out RedeemedBootstrapToken
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		userID, err := s.store.LookupUserIDBySubject(ctx, tx, subject, callerOrgID)
		if err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return ErrBootstrapUserNotProvisioned
			}
			return err
		}

		tok, err := s.store.GetActiveBootstrapTokenByHash(ctx, tx, hash, now)
		if err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return ErrInvalidBootstrapToken
			}
			return err
		}
		// Cross-org safety: if the JWT claimer's org doesn't match
		// the token's org, refuse — and do NOT consume the token.
		// An attacker with a valid (different-org) JWT and a guessed
		// cleartext must not be able to burn a victim's token.
		if tok.OrgID != callerOrgID {
			return ErrInvalidBootstrapToken
		}
		if err := s.store.RedeemBootstrapToken(ctx, tx, tok.ID, userID, now); err != nil {
			if errors.Is(err, store.ErrNotFound) {
				return ErrInvalidBootstrapToken
			}
			return err
		}
		out = RedeemedBootstrapToken{ID: tok.ID, OrgID: tok.OrgID}
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        tok.OrgID,
			UserSub:      subject,
			Action:       AuditActionSetupBootstrapClaim,
			ResourceType: AuditResourceOrganization,
			ResourceID:   tok.ID,
		})
		return nil
	})
	if err != nil {
		// Pass-through sentinel errors; only map storage-shaped ones.
		if errors.Is(err, ErrInvalidBootstrapToken) ||
			errors.Is(err, ErrBootstrapUserNotProvisioned) ||
			errors.Is(err, ErrInvalidInput) {
			return RedeemedBootstrapToken{}, err
		}
		return RedeemedBootstrapToken{}, mapSetupStoreError(err)
	}
	return out, nil
}

// SeedBootstrapTokenIfNeeded is the boot-time helper that lets
// cmd/server materialize a setup_bootstrap_tokens row from an
// operator-supplied cleartext (BUILDOS_BOOTSTRAP_TOKEN env). Idempotent
// — relies on the schema's UNIQUE(token_hash) constraint to swallow
// re-boot inserts of the same cleartext.
//
// Returns (false, nil) when no fork-zero org exists yet, when the
// fork-zero org has already finished onboarding, or when an active
// token already exists for the cleartext. Returns (true, nil) when a
// fresh row landed. Returns (false, err) on storage failure or on
// malformed cleartext (caught at boot so a bad env var fails fast).
//
// orgID may be uuid.Nil; when Nil the service picks the first
// onboarding-incomplete organization. The Nil-fallback exists because
// cmd/server doesn't always know the fork's org_id at boot — in
// single-tenant forks there is exactly one organizations row, freshly
// seeded by migration 010.
func (s *SetupService) SeedBootstrapTokenIfNeeded(ctx context.Context, cleartext string, orgID uuid.UUID, ttl time.Duration) (bool, error) {
	if cleartext == "" {
		return false, nil // not configured — silent no-op
	}
	// Format validation: base64url-no-pad of 32 bytes is exactly 43
	// chars. Catches operator typos at boot rather than at redeem.
	if l := len(cleartext); l != 43 {
		return false, fmt.Errorf("%w: cleartext bootstrap token must be 43 base64url chars (got %d)", ErrInvalidInput, l)
	}
	if _, err := base64.RawURLEncoding.DecodeString(cleartext); err != nil {
		return false, fmt.Errorf("%w: cleartext bootstrap token is not base64url: %v", ErrInvalidInput, err)
	}
	if ttl <= 0 {
		ttl = DefaultBootstrapTokenTTL
	}

	hash := hashBootstrapToken(cleartext)
	expires := s.now().Add(ttl)

	var seeded bool
	err := pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		target := orgID
		if target == uuid.Nil {
			// Pick the first onboarding-incomplete org. Strict in
			// single-tenant forks (exactly one org row). For
			// multi-tenant variants the caller must pass orgID.
			err := tx.QueryRow(ctx, `
				SELECT id FROM organizations
				WHERE onboarding_complete = false
				ORDER BY created_at ASC
				LIMIT 1`).Scan(&target)
			if err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					// All orgs onboarded — nothing to seed.
					return nil
				}
				return fmt.Errorf("find fork-zero org: %w", err)
			}
		} else {
			cp, gerr := s.store.GetCompanyProfile(ctx, tx, target)
			if gerr != nil {
				return gerr
			}
			if cp.OnboardingComplete {
				return nil
			}
		}

		_, qErr := s.store.CreateBootstrapToken(ctx, tx, store.CreateBootstrapTokenParams{
			OrgID:     target,
			TokenHash: hash,
			ExpiresAt: expires,
		})
		if qErr != nil {
			// SQLSTATE 23505: token already exists — idempotent
			// re-boot. Not an error.
			var pgErr *pgconn.PgError
			if errors.As(qErr, &pgErr) && pgErr.Code == "23505" {
				return nil
			}
			return fmt.Errorf("seed bootstrap token: %w", qErr)
		}
		seeded = true
		s.audit.Record(ctx, tx, AuditEntry{
			OrgID:        target,
			UserSub:      "system:boot",
			Action:       AuditActionSetupBootstrapIssue,
			ResourceType: AuditResourceOrganization,
			ResourceID:   target,
		})
		return nil
	})
	if err != nil {
		if errors.Is(err, ErrInvalidInput) {
			return false, err
		}
		return false, mapSetupStoreError(err)
	}
	return seeded, nil
}

// IsOnboardingComplete is a cheap read-only check used by the
// SetupGate middleware on every operational request. Single-row
// SELECT on a primary key, no tx overhead — pgx.Pool.QueryRow is
// fine here.
func (s *SetupService) IsOnboardingComplete(ctx context.Context, orgID uuid.UUID) (bool, error) {
	if orgID == uuid.Nil {
		return false, fmt.Errorf("%w: org_id required", ErrInvalidInput)
	}
	var done bool
	err := s.pool.QueryRow(ctx, `SELECT onboarding_complete FROM organizations WHERE id = $1`, orgID).Scan(&done)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, store.ErrNotFound
		}
		return false, fmt.Errorf("read onboarding state: %w", err)
	}
	return done, nil
}

// ---------- helpers ----------

// guardNotComplete short-circuits any wizard mutation once the org
// has flipped onboarding_complete=true. Defense against a stale UI
// re-submitting steps after completion.
func (s *SetupService) guardNotComplete(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) error {
	cp, err := s.store.GetCompanyProfile(ctx, tx, orgID)
	if err != nil {
		return err
	}
	if cp.OnboardingComplete {
		return ErrSetupAlreadyComplete
	}
	return nil
}

// mapSetupStoreError translates pgx unique-violation (SQLSTATE 23505)
// into ErrInvalidInput so the HTTP handler maps to 409 / 422 rather
// than 500. Falls through to the package-shared mapStoreError for
// other cases (store.ErrNotFound → ErrNotFound).
func mapSetupStoreError(err error) error {
	if err == nil {
		return nil
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" {
		return fmt.Errorf("%w: %s", ErrInvalidInput, pgErr.ConstraintName)
	}
	return mapStoreError(err)
}

// atLeastOneNonNil returns true when at least one pointer is non-nil.
// Used in PATCH-style validators where every field is optional but
// the call must mutate something.
func atLeastOneNonNil(ps ...*string) bool {
	for _, p := range ps {
		if p != nil {
			return true
		}
	}
	return false
}

// looksLikeRegion accepts a relaxed ISO-3166-2 shape: 2..3 letters,
// optional "-", 2..3 letters/digits. Not a hard validator; the goal
// is to catch obvious typos at wizard time. The CPM physics engine
// doesn't parse this — it's an informational metadata field.
func looksLikeRegion(s string) bool {
	if len(s) < 2 || len(s) > 8 {
		return false
	}
	for _, r := range s {
		if !(r == '-' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

// isShortCode validates trade-category codes — alphanumeric +
// underscore/hyphen, length in [min, max].
func isShortCode(s string, min, max int) bool {
	if len(s) < min || len(s) > max {
		return false
	}
	for _, r := range s {
		if !(r == '_' || r == '-' || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

// looksLikeCSICode accepts the CSI MasterFormat shape: two-digit
// segments separated by hyphens, 2..3 segments total (e.g. "03-30"
// or "03-30-00"). Strict enough to catch typos, loose enough to
// allow the parent-level codes the wizard seeds.
func looksLikeCSICode(s string) bool {
	parts := strings.Split(s, "-")
	if len(parts) < 2 || len(parts) > 3 {
		return false
	}
	for _, p := range parts {
		if len(p) != 2 {
			return false
		}
		for _, r := range p {
			if r < '0' || r > '9' {
				return false
			}
		}
	}
	return true
}

// generateBootstrapTokenCleartext returns 32 random bytes encoded as
// base64url-no-pad (43 chars). The encoding is URL-safe so operators
// can paste the token into a curl command without quote-escaping.
func generateBootstrapTokenCleartext() (string, error) {
	buf := make([]byte, bootstrapTokenByteLen)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// hashBootstrapToken returns the hex-encoded sha256 hash of cleartext.
// Deterministic so setup_bootstrap_tokens.token_hash supports unique-
// index lookup; cryptographically sufficient because cleartext has
// 256 bits of CSPRNG entropy — no offline crack is feasible.
func hashBootstrapToken(cleartext string) string {
	sum := sha256.Sum256([]byte(cleartext))
	const hex = "0123456789abcdef"
	out := make([]byte, len(sum)*2)
	for i, b := range sum {
		out[i*2] = hex[b>>4]
		out[i*2+1] = hex[b&0x0f]
	}
	return string(out)
}
