package main

import (
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-jose/go-jose/v4"

	"github.com/futurebuildai/buildos/internal/a2asigner"
)

// The end-to-end test: keypair generated by fork-init must be usable
// by the a2asigner package (production signing path) AND the resulting
// JWS must verify against the public key in the JWKS file. If this
// passes, an operator's fresh fork-init run produces artifacts the
// runtime can immediately consume.
func TestForkInit_KeypairRoundTripsThroughSigner(t *testing.T) {
	dir := t.TempDir()
	const kid = "test-kid-1"
	const orgID = "11111111-1111-1111-1111-111111111111"

	// Deterministic seed for test speed; production always uses
	// crypto/rand. The seed value is irrelevant — any non-zero works.
	if err := run(dir, kid, orgID, 2048, 12345, true); err != nil {
		t.Fatalf("run: %v", err)
	}

	// Confirm all five artifacts landed.
	for _, name := range []string{"private.pem", "public.pem", "jwks.json", "bootstrap_token.txt", "fork.yaml"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("missing artifact %s: %v", name, err)
		}
	}

	// 1) Sign something with private.pem via the production
	//    a2asigner package.
	signer, err := a2asigner.NewSignerFromFile(filepath.Join(dir, "private.pem"), kid)
	if err != nil {
		t.Fatalf("a2asigner.NewSignerFromFile: %v", err)
	}
	payload := []byte(`{"event":"test","kid":"` + kid + `"}`)
	sig, err := signer.SignDetached(payload)
	if err != nil {
		t.Fatalf("SignDetached: %v", err)
	}
	if !strings.Contains(sig, "..") {
		t.Errorf("signature missing detached marker: %s", sig)
	}

	// 2) Verify the signature against the public key in the JWKS.
	jwksBytes, err := os.ReadFile(filepath.Join(dir, "jwks.json"))
	if err != nil {
		t.Fatalf("read jwks.json: %v", err)
	}
	var ks jose.JSONWebKeySet
	if err := json.Unmarshal(jwksBytes, &ks); err != nil {
		t.Fatalf("unmarshal jwks: %v", err)
	}
	if len(ks.Keys) != 1 {
		t.Fatalf("jwks key count = %d, want 1", len(ks.Keys))
	}
	pub, ok := ks.Keys[0].Key.(*rsa.PublicKey)
	if !ok {
		t.Fatalf("jwks[0].Key is %T, want *rsa.PublicKey", ks.Keys[0].Key)
	}
	if ks.Keys[0].KeyID != kid {
		t.Errorf("jwks kid = %q, want %q", ks.Keys[0].KeyID, kid)
	}
	if ks.Keys[0].Algorithm != "RS256" {
		t.Errorf("jwks alg = %q, want RS256", ks.Keys[0].Algorithm)
	}

	jws, err := jose.ParseDetached(sig, payload, []jose.SignatureAlgorithm{jose.RS256})
	if err != nil {
		t.Fatalf("ParseDetached: %v", err)
	}
	if _, err := jws.Verify(pub); err != nil {
		t.Errorf("jws.Verify against jwks public key: %v", err)
	}

	// 3) public.pem should also match the JWKS key.
	pubPEM, err := os.ReadFile(filepath.Join(dir, "public.pem"))
	if err != nil {
		t.Fatalf("read public.pem: %v", err)
	}
	block, _ := pem.Decode(pubPEM)
	if block == nil {
		t.Fatal("public.pem: no PEM block")
	}
	if block.Type != "PUBLIC KEY" {
		t.Errorf("public.pem block type = %q, want PUBLIC KEY", block.Type)
	}
}

func TestForkInit_PrivatePEMHasRestrictiveMode(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-1", "", 2048, 99, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "private.pem"))
	if err != nil {
		t.Fatalf("stat private.pem: %v", err)
	}
	// Ensure the file is owner-only readable. Fork operators who
	// look at file permissions should see 0600 (or stricter).
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("private.pem perm = %o, want 600", mode)
	}
}

// TestForkInit_BootstrapTokenIsCSPRNGAndOwnerOnly pins the two
// security-relevant properties of bootstrap_token.txt: file mode
// MUST be 0600 (otherwise a shared-host operator leaks the token to
// any process running as the same user via /tmp), and the cleartext
// MUST decode to exactly 32 bytes (256 bits of CSPRNG entropy is
// what makes a fast deterministic SHA-256 hash on the DB side safe
// against offline brute-force; cutting that short breaks the
// security model in internal/service/setup.go).
func TestForkInit_BootstrapTokenIsCSPRNGAndOwnerOnly(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-btok", "", 2048, 42, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "bootstrap_token.txt"))
	if err != nil {
		t.Fatalf("stat bootstrap_token.txt: %v", err)
	}
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("bootstrap_token.txt perm = %o, want 600", mode)
	}
	body, err := os.ReadFile(filepath.Join(dir, "bootstrap_token.txt"))
	if err != nil {
		t.Fatalf("read bootstrap_token.txt: %v", err)
	}
	cleartext := strings.TrimRight(string(body), "\n")
	decoded, err := base64.RawURLEncoding.DecodeString(cleartext)
	if err != nil {
		t.Fatalf("bootstrap_token.txt is not base64url-no-pad: %v\nbody=%q", err, cleartext)
	}
	if len(decoded) != bootstrapTokenByteLen {
		t.Errorf("bootstrap_token decoded len = %d, want %d (256 bits CSPRNG)", len(decoded), bootstrapTokenByteLen)
	}
}

// TestForkInit_SkipBootstrapTokenSuppressesArtifact pins that the
// --skip-bootstrap-token CLI flag (rotation-only mode) does not
// leave a stale bootstrap_token.txt next to the rotated keypair —
// otherwise operators rotating signing keys would inadvertently
// regenerate a claim token that re-arms the wizard's bootstrap path
// after onboarding has already completed.
func TestForkInit_SkipBootstrapTokenSuppressesArtifact(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-rotate", "", 2048, 7, false); err != nil {
		t.Fatalf("run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "bootstrap_token.txt")); !os.IsNotExist(err) {
		t.Errorf("bootstrap_token.txt should NOT exist with emit=false (err=%v)", err)
	}
	// fork.yaml should reflect the operator's choice.
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read fork.yaml: %v", err)
	}
	if !strings.Contains(string(body), "bootstrap_token_emitted: false") {
		t.Errorf("fork.yaml should record bootstrap_token_emitted: false; got:\n%s", body)
	}
	if strings.Contains(string(body), "BUILDOS_BOOTSTRAP_TOKEN") {
		t.Errorf("fork.yaml should NOT mention BUILDOS_BOOTSTRAP_TOKEN when skipped; got:\n%s", body)
	}
}

func TestForkInit_ForkYAMLNamesEnvVars(t *testing.T) {
	// fork.yaml is the operator-readable artifact. It must list the
	// exact env-var names BuildOS reads so the operator wiring up
	// a deployment doesn't have to re-derive them from source.
	dir := t.TempDir()
	const kid = "yaml-test-kid"
	const orgID = "22222222-2222-2222-2222-222222222222"
	if err := run(dir, kid, orgID, 2048, 7, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	str := string(body)
	for _, want := range []string{
		`kid:               "yaml-test-kid"`,
		`default_org_id:    "` + orgID + `"`,
		"A2A_KEY_ID:           yaml-test-kid",
		"A2A_SIGNING_KEY_PATH:",
		"DEFAULT_ORG_ID:       " + orgID,
		"BUILDOS_BOOTSTRAP_TOKEN",
		"key_size_bits:     2048",
		"bootstrap_token_emitted: true",
	} {
		if !strings.Contains(str, want) {
			t.Errorf("fork.yaml missing %q\n--full--\n%s", want, str)
		}
	}
}

func TestForkInit_OmittedOrgIDPlaceholder(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-no-org", "", 2048, 11, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if !strings.Contains(string(body), "<set DEFAULT_ORG_ID at deploy time>") {
		t.Errorf("fork.yaml should include placeholder for missing org_id; got:\n%s", body)
	}
}
