package main

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The end-to-end test: the keypair generated by fork-init must be a
// usable RS256 JWT signing key — private.pem signs, public.pem
// verifies — and vault_master_key.txt must decode to a 32-byte
// AES-256 key. If this passes, an operator's fresh fork-init run
// produces artifacts cmd/server can immediately consume to mint JWTs
// and seal the credential vault.
func TestForkInit_KeypairRoundTrips(t *testing.T) {
	dir := t.TempDir()
	const kid = "test-kid-1"
	const orgID = "11111111-1111-1111-1111-111111111111"

	// Deterministic seed for test speed; production always uses
	// crypto/rand. The seed value is irrelevant — any non-zero works.
	if err := run(dir, kid, orgID, 2048, 12345, true); err != nil {
		t.Fatalf("run: %v", err)
	}

	// Confirm all five artifacts landed.
	for _, name := range []string{"private.pem", "public.pem", "vault_master_key.txt", "bootstrap_token.txt", "fork.yaml"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("missing artifact %s: %v", name, err)
		}
	}

	// 1) Parse private.pem as a PKCS#8 RSA private key.
	priv := parsePrivatePEM(t, filepath.Join(dir, "private.pem"))

	// 2) Parse public.pem as an SPKI RSA public key and confirm it
	//    matches the private key (same modulus + exponent).
	pub := parsePublicPEM(t, filepath.Join(dir, "public.pem"))
	if pub.N.Cmp(priv.N) != 0 || pub.E != priv.E {
		t.Errorf("public.pem does not match private.pem")
	}

	// 3) Sign with the private key (RS256 = RSASSA-PKCS1v15 + SHA-256)
	//    and verify with the public key. This is the exact operation
	//    the JWT issuer/verifier perform at runtime.
	payload := []byte(`{"event":"test","kid":"` + kid + `"}`)
	digest := sha256.Sum256(payload)
	sig, err := rsa.SignPKCS1v15(rand.Reader, priv, crypto.SHA256, digest[:])
	if err != nil {
		t.Fatalf("SignPKCS1v15: %v", err)
	}
	if err := rsa.VerifyPKCS1v15(pub, crypto.SHA256, digest[:], sig); err != nil {
		t.Errorf("VerifyPKCS1v15 against public.pem: %v", err)
	}

	// 4) vault_master_key.txt must decode (standard base64) to a
	//    32-byte AES-256 key.
	keyBody, err := os.ReadFile(filepath.Join(dir, "vault_master_key.txt"))
	if err != nil {
		t.Fatalf("read vault_master_key.txt: %v", err)
	}
	keyDecoded, err := base64.StdEncoding.DecodeString(strings.TrimRight(string(keyBody), "\n"))
	if err != nil {
		t.Fatalf("vault_master_key.txt is not standard-base64: %v", err)
	}
	if len(keyDecoded) != vaultMasterKeyByteLen {
		t.Errorf("vault master key decoded len = %d, want %d", len(keyDecoded), vaultMasterKeyByteLen)
	}
}

func parsePrivatePEM(t *testing.T, path string) *rsa.PrivateKey {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	block, _ := pem.Decode(b)
	if block == nil {
		t.Fatalf("%s: no PEM block", path)
	}
	if block.Type != "PRIVATE KEY" {
		t.Errorf("%s block type = %q, want PRIVATE KEY", path, block.Type)
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		t.Fatalf("ParsePKCS8PrivateKey: %v", err)
	}
	rsaKey, ok := key.(*rsa.PrivateKey)
	if !ok {
		t.Fatalf("private key is %T, want *rsa.PrivateKey", key)
	}
	return rsaKey
}

func parsePublicPEM(t *testing.T, path string) *rsa.PublicKey {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	block, _ := pem.Decode(b)
	if block == nil {
		t.Fatalf("%s: no PEM block", path)
	}
	if block.Type != "PUBLIC KEY" {
		t.Errorf("%s block type = %q, want PUBLIC KEY", path, block.Type)
	}
	key, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		t.Fatalf("ParsePKIXPublicKey: %v", err)
	}
	rsaKey, ok := key.(*rsa.PublicKey)
	if !ok {
		t.Fatalf("public key is %T, want *rsa.PublicKey", key)
	}
	return rsaKey
}

func TestForkInit_PrivatePEMHasRestrictiveMode(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-1", "", 2048, 99, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "private.pem"))
	if err != nil {
		t.Fatalf("stat private.pem: %v", err)
	}
	// Ensure the file is owner-only readable. Fork operators who
	// look at file permissions should see 0600 (or stricter).
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("private.pem perm = %o, want 600", mode)
	}
}

// TestForkInit_VaultMasterKeyOwnerOnly pins that vault_master_key.txt
// is owner-only readable (0600). It carries the AES-256 key that seals
// every BYOK credential; a shared-host operator must not leak it to
// other processes running as the same user via the output dir.
func TestForkInit_VaultMasterKeyOwnerOnly(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-vault", "", 2048, 31, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "vault_master_key.txt"))
	if err != nil {
		t.Fatalf("stat vault_master_key.txt: %v", err)
	}
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("vault_master_key.txt perm = %o, want 600", mode)
	}
}

// TestForkInit_BootstrapTokenIsCSPRNGAndOwnerOnly pins the two
// security-relevant properties of bootstrap_token.txt: file mode
// MUST be 0600 (otherwise a shared-host operator leaks the token to
// any process running as the same user via /tmp), and the cleartext
// MUST decode to exactly 32 bytes (256 bits of CSPRNG entropy is
// what makes a fast deterministic SHA-256 hash on the DB side safe
// against offline brute-force; cutting that short breaks the
// security model in internal/service/setup.go).
func TestForkInit_BootstrapTokenIsCSPRNGAndOwnerOnly(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-btok", "", 2048, 42, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	st, err := os.Stat(filepath.Join(dir, "bootstrap_token.txt"))
	if err != nil {
		t.Fatalf("stat bootstrap_token.txt: %v", err)
	}
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("bootstrap_token.txt perm = %o, want 600", mode)
	}
	body, err := os.ReadFile(filepath.Join(dir, "bootstrap_token.txt"))
	if err != nil {
		t.Fatalf("read bootstrap_token.txt: %v", err)
	}
	cleartext := strings.TrimRight(string(body), "\n")
	decoded, err := base64.RawURLEncoding.DecodeString(cleartext)
	if err != nil {
		t.Fatalf("bootstrap_token.txt is not base64url-no-pad: %v\nbody=%q", err, cleartext)
	}
	if len(decoded) != bootstrapTokenByteLen {
		t.Errorf("bootstrap_token decoded len = %d, want %d (256 bits CSPRNG)", len(decoded), bootstrapTokenByteLen)
	}
}

// TestForkInit_SkipBootstrapTokenSuppressesArtifact pins that the
// --skip-bootstrap-token CLI flag (rotation-only mode) does not
// leave a stale bootstrap_token.txt next to the rotated keypair —
// otherwise operators rotating signing keys would inadvertently
// regenerate a claim token that re-arms the wizard's bootstrap path
// after onboarding has already completed.
func TestForkInit_SkipBootstrapTokenSuppressesArtifact(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-rotate", "", 2048, 7, false); err != nil {
		t.Fatalf("run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "bootstrap_token.txt")); !os.IsNotExist(err) {
		t.Errorf("bootstrap_token.txt should NOT exist with emit=false (err=%v)", err)
	}
	// fork.yaml should reflect the operator's choice.
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read fork.yaml: %v", err)
	}
	if !strings.Contains(string(body), "bootstrap_token_emitted: false") {
		t.Errorf("fork.yaml should record bootstrap_token_emitted: false; got:\n%s", body)
	}
	if strings.Contains(string(body), "BUILDOS_BOOTSTRAP_TOKEN") {
		t.Errorf("fork.yaml should NOT mention BUILDOS_BOOTSTRAP_TOKEN when skipped; got:\n%s", body)
	}
}

func TestForkInit_ForkYAMLNamesEnvVars(t *testing.T) {
	// fork.yaml is the operator-readable artifact. It must list the
	// exact env-var names BuildOS reads so the operator wiring up
	// a deployment doesn't have to re-derive them from source.
	dir := t.TempDir()
	const kid = "yaml-test-kid"
	const orgID = "22222222-2222-2222-2222-222222222222"
	if err := run(dir, kid, orgID, 2048, 7, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	str := string(body)
	for _, want := range []string{
		`kid:               "yaml-test-kid"`,
		`org_id:            "` + orgID + `"`,
		"JWT_KEY_ID:           yaml-test-kid",
		"JWT_PRIVATE_KEY_PEM:",
		"JWT_PUBLIC_KEY_PEM:",
		"VAULT_MASTER_KEY:",
		"BUILDOS_BOOTSTRAP_TOKEN",
		"key_size_bits:     2048",
		"bootstrap_token_emitted: true",
	} {
		if !strings.Contains(str, want) {
			t.Errorf("fork.yaml missing %q\n--full--\n%s", want, str)
		}
	}
}

func TestForkInit_OmittedOrgIDPlaceholder(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "kid-no-org", "", 2048, 11, true); err != nil {
		t.Fatalf("run: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "fork.yaml"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if !strings.Contains(string(body), "<assigned during onboarding>") {
		t.Errorf("fork.yaml should include placeholder for missing org_id; got:\n%s", body)
	}
}
