package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/futurebuildai/buildos/internal/models"
)

// SetupStore manages the rows the onboarding wizard reads + writes:
//   - organizations company-profile columns (migration 010 extension)
//   - setup_bootstrap_tokens
//   - trade_categories
//   - cost_codes
//   - working_calendars + holiday_overrides
//   - permit_jurisdictions
//
// All methods take a pgx.Tx so the service layer can compose wizard
// steps inside one transaction with the audit-log write (matches the
// pattern in schedule.go, a2a.go).
type SetupStore struct{}

// NewSetupStore constructs a SetupStore. Stateless — safe to share.
func NewSetupStore() *SetupStore { return &SetupStore{} }

// ---------- organizations company profile ----------

// UpdateCompanyProfileParams is the input for the wizard's step-1
// company-info submission. Every field is optional at the SQL level
// (matches the migration's nullable columns); the service is expected
// to enforce step-completion invariants (e.g., LegalName + Region
// required) before calling.
type UpdateCompanyProfileParams struct {
	OrgID       uuid.UUID
	LegalName   *string
	Address     *string
	EIN         *string
	CompanyType *string
	Region      *string
}

// UpdateCompanyProfile writes the org-level company-info fields.
// COALESCE allows the wizard to PATCH individual fields without losing
// values from a prior submission — useful when the wizard is resumed
// after a partial submit.
func (s *SetupStore) UpdateCompanyProfile(ctx context.Context, tx pgx.Tx, p UpdateCompanyProfileParams) error {
	cmd, err := tx.Exec(ctx, `
		UPDATE organizations SET
			legal_name   = COALESCE($2, legal_name),
			address      = COALESCE($3, address),
			ein          = COALESCE($4, ein),
			company_type = COALESCE($5, company_type),
			region       = COALESCE($6, region),
			updated_at   = now()
		WHERE id = $1`,
		p.OrgID, p.LegalName, p.Address, p.EIN, p.CompanyType, p.Region,
	)
	if err != nil {
		return fmt.Errorf("update company profile: %w", err)
	}
	if cmd.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// GetCompanyProfile reads the org-level company-info fields plus the
// onboarding gate state. Used by GET /setup/state to render the
// wizard's current progress.
func (s *SetupStore) GetCompanyProfile(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) (models.CompanyProfile, error) {
	var cp models.CompanyProfile
	err := tx.QueryRow(ctx, `
		SELECT legal_name, address, ein, company_type, region,
		       onboarding_complete, onboarding_completed_at
		FROM organizations
		WHERE id = $1`, orgID,
	).Scan(
		&cp.LegalName, &cp.Address, &cp.EIN, &cp.CompanyType, &cp.Region,
		&cp.OnboardingComplete, &cp.OnboardingCompletedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return models.CompanyProfile{}, ErrNotFound
		}
		return models.CompanyProfile{}, fmt.Errorf("get company profile: %w", err)
	}
	return cp, nil
}

// CompleteOnboarding flips onboarding_complete=true and stamps the
// completion time. Idempotent — calling twice is a no-op on the second
// call (completed_at is not advanced). Returns ErrNotFound if the org
// row is missing.
func (s *SetupStore) CompleteOnboarding(ctx context.Context, tx pgx.Tx, orgID uuid.UUID, now time.Time) error {
	cmd, err := tx.Exec(ctx, `
		UPDATE organizations SET
			onboarding_complete      = true,
			onboarding_completed_at  = COALESCE(onboarding_completed_at, $2),
			updated_at               = now()
		WHERE id = $1`, orgID, now)
	if err != nil {
		return fmt.Errorf("complete onboarding: %w", err)
	}
	if cmd.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ---------- setup_bootstrap_tokens ----------

// CreateBootstrapTokenParams stores a pre-hashed token. The cleartext
// token is generated by the caller and shown ONCE in fork.yaml; only
// the hash lands in the DB.
type CreateBootstrapTokenParams struct {
	OrgID     uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// CreateBootstrapToken persists a one-shot bootstrap token. The unique
// index on token_hash means a hash collision is a constraint violation
// — extremely unlikely with argon2id but surface as a generic error.
func (s *SetupStore) CreateBootstrapToken(ctx context.Context, tx pgx.Tx, p CreateBootstrapTokenParams) (uuid.UUID, error) {
	var id uuid.UUID
	err := tx.QueryRow(ctx, `
		INSERT INTO setup_bootstrap_tokens (org_id, token_hash, expires_at)
		VALUES ($1, $2, $3)
		RETURNING id`, p.OrgID, p.TokenHash, p.ExpiresAt,
	).Scan(&id)
	if err != nil {
		return uuid.Nil, fmt.Errorf("insert bootstrap token: %w", err)
	}
	return id, nil
}

// GetActiveBootstrapTokenByHash looks up an unredeemed, unexpired token
// by its hash. Returns ErrNotFound when no row matches, even if the
// token exists but is redeemed or expired — the service layer never
// needs to distinguish those cases.
func (s *SetupStore) GetActiveBootstrapTokenByHash(ctx context.Context, tx pgx.Tx, hash string, now time.Time) (models.SetupBootstrapToken, error) {
	var t models.SetupBootstrapToken
	err := tx.QueryRow(ctx, `
		SELECT id, org_id, token_hash, issued_at, expires_at, redeemed_at, redeemed_by
		FROM setup_bootstrap_tokens
		WHERE token_hash = $1
		  AND redeemed_at IS NULL
		  AND expires_at > $2`, hash, now,
	).Scan(&t.ID, &t.OrgID, &t.TokenHash, &t.IssuedAt, &t.ExpiresAt, &t.RedeemedAt, &t.RedeemedBy)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return models.SetupBootstrapToken{}, ErrNotFound
		}
		return models.SetupBootstrapToken{}, fmt.Errorf("get bootstrap token: %w", err)
	}
	return t, nil
}

// RedeemBootstrapToken marks a token redeemed. The WHERE clause double-
// checks redeemed_at IS NULL so a concurrent redemption attempt (two
// admins racing on the same token) sees RowsAffected=0 and the service
// layer rolls back rather than minting a second owner.
func (s *SetupStore) RedeemBootstrapToken(ctx context.Context, tx pgx.Tx, tokenID, redeemedBy uuid.UUID, now time.Time) error {
	cmd, err := tx.Exec(ctx, `
		UPDATE setup_bootstrap_tokens SET
			redeemed_at = $2,
			redeemed_by = $3
		WHERE id = $1
		  AND redeemed_at IS NULL`, tokenID, now, redeemedBy)
	if err != nil {
		return fmt.Errorf("redeem bootstrap token: %w", err)
	}
	if cmd.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ---------- trade_categories ----------

// CreateTradeCategoryParams is the input for inserting a trade category.
type CreateTradeCategoryParams struct {
	OrgID       uuid.UUID
	Code        string
	Name        string
	Description *string
	IsDefault   bool
}

// CreateTradeCategory inserts a row. UNIQUE(org_id, code) means a
// duplicate code returns a pgx unique-violation error — the service
// is expected to either upsert or pre-check.
func (s *SetupStore) CreateTradeCategory(ctx context.Context, tx pgx.Tx, p CreateTradeCategoryParams) (models.TradeCategory, error) {
	var t models.TradeCategory
	err := tx.QueryRow(ctx, `
		INSERT INTO trade_categories (org_id, code, name, description, is_default)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, org_id, code, name, description, is_default, created_at, updated_at`,
		p.OrgID, p.Code, p.Name, p.Description, p.IsDefault,
	).Scan(&t.ID, &t.OrgID, &t.Code, &t.Name, &t.Description, &t.IsDefault, &t.CreatedAt, &t.UpdatedAt)
	if err != nil {
		return models.TradeCategory{}, fmt.Errorf("insert trade category: %w", err)
	}
	return t, nil
}

// ListTradeCategories returns all trade categories for an org, ordered
// by is_default DESC, name ASC. Defaults float to the top of the
// wizard's review screen so operators see the seeded set first.
func (s *SetupStore) ListTradeCategories(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) ([]models.TradeCategory, error) {
	rows, err := tx.Query(ctx, `
		SELECT id, org_id, code, name, description, is_default, created_at, updated_at
		FROM trade_categories
		WHERE org_id = $1
		ORDER BY is_default DESC, name ASC`, orgID)
	if err != nil {
		return nil, fmt.Errorf("list trade categories: %w", err)
	}
	defer rows.Close()

	var out []models.TradeCategory
	for rows.Next() {
		var t models.TradeCategory
		if err := rows.Scan(&t.ID, &t.OrgID, &t.Code, &t.Name, &t.Description, &t.IsDefault, &t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan trade category: %w", err)
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

// ---------- cost_codes ----------

// CreateCostCodeParams is the input for inserting a cost code.
type CreateCostCodeParams struct {
	OrgID      uuid.UUID
	Code       string
	Name       string
	Division   string
	ParentCode *string
	IsDefault  bool
}

// CreateCostCode inserts a row. UNIQUE(org_id, code) — duplicate code
// surfaces as a unique-violation.
func (s *SetupStore) CreateCostCode(ctx context.Context, tx pgx.Tx, p CreateCostCodeParams) (models.CostCode, error) {
	var c models.CostCode
	err := tx.QueryRow(ctx, `
		INSERT INTO cost_codes (org_id, code, name, division, parent_code, is_default)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, org_id, code, name, division, parent_code, is_default, created_at, updated_at`,
		p.OrgID, p.Code, p.Name, p.Division, p.ParentCode, p.IsDefault,
	).Scan(&c.ID, &c.OrgID, &c.Code, &c.Name, &c.Division, &c.ParentCode, &c.IsDefault, &c.CreatedAt, &c.UpdatedAt)
	if err != nil {
		return models.CostCode{}, fmt.Errorf("insert cost code: %w", err)
	}
	return c, nil
}

// ListCostCodes returns all cost codes for an org, ordered by code ASC
// (MasterFormat division-section-subsection is naturally sorted).
func (s *SetupStore) ListCostCodes(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) ([]models.CostCode, error) {
	rows, err := tx.Query(ctx, `
		SELECT id, org_id, code, name, division, parent_code, is_default, created_at, updated_at
		FROM cost_codes
		WHERE org_id = $1
		ORDER BY code ASC`, orgID)
	if err != nil {
		return nil, fmt.Errorf("list cost codes: %w", err)
	}
	defer rows.Close()

	var out []models.CostCode
	for rows.Next() {
		var c models.CostCode
		if err := rows.Scan(&c.ID, &c.OrgID, &c.Code, &c.Name, &c.Division, &c.ParentCode, &c.IsDefault, &c.CreatedAt, &c.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan cost code: %w", err)
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// ---------- working_calendars + holiday_overrides ----------

// CreateWorkingCalendarParams is the input for inserting a working calendar.
type CreateWorkingCalendarParams struct {
	OrgID            uuid.UUID
	Name             string
	Timezone         string
	WorkingDaysMask  int16
	DailyWorkMinutes int
	IsDefault        bool
}

// CreateWorkingCalendar inserts a row. If IsDefault=true and a default
// already exists for the org, the partial unique index
// idx_working_calendars_org_default_unique surfaces a unique-violation;
// the service should clear the prior default first.
func (s *SetupStore) CreateWorkingCalendar(ctx context.Context, tx pgx.Tx, p CreateWorkingCalendarParams) (models.WorkingCalendar, error) {
	var c models.WorkingCalendar
	err := tx.QueryRow(ctx, `
		INSERT INTO working_calendars (org_id, name, timezone, working_days_mask, daily_work_minutes, is_default)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, org_id, name, timezone, working_days_mask, daily_work_minutes, is_default, created_at, updated_at`,
		p.OrgID, p.Name, p.Timezone, p.WorkingDaysMask, p.DailyWorkMinutes, p.IsDefault,
	).Scan(&c.ID, &c.OrgID, &c.Name, &c.Timezone, &c.WorkingDaysMask, &c.DailyWorkMinutes, &c.IsDefault, &c.CreatedAt, &c.UpdatedAt)
	if err != nil {
		return models.WorkingCalendar{}, fmt.Errorf("insert working calendar: %w", err)
	}
	return c, nil
}

// GetDefaultWorkingCalendar returns the org's default calendar.
// Returns ErrNotFound if no default has been set yet (wizard step 5
// not completed). The CPM physics engine fetches this once per
// schedule recalc; it's the SWIM step's source of working days.
func (s *SetupStore) GetDefaultWorkingCalendar(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) (models.WorkingCalendar, error) {
	var c models.WorkingCalendar
	err := tx.QueryRow(ctx, `
		SELECT id, org_id, name, timezone, working_days_mask, daily_work_minutes, is_default, created_at, updated_at
		FROM working_calendars
		WHERE org_id = $1 AND is_default = true`, orgID,
	).Scan(&c.ID, &c.OrgID, &c.Name, &c.Timezone, &c.WorkingDaysMask, &c.DailyWorkMinutes, &c.IsDefault, &c.CreatedAt, &c.UpdatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return models.WorkingCalendar{}, ErrNotFound
		}
		return models.WorkingCalendar{}, fmt.Errorf("get default working calendar: %w", err)
	}
	return c, nil
}

// CreateHolidayOverrideParams is the input for inserting a holiday.
type CreateHolidayOverrideParams struct {
	CalendarID  uuid.UUID
	OrgID       uuid.UUID
	HolidayDate time.Time
	Name        string
}

// CreateHolidayOverride inserts a row. UNIQUE(calendar_id, holiday_date)
// — the service is expected to filter for duplicates client-side or
// catch the unique-violation.
func (s *SetupStore) CreateHolidayOverride(ctx context.Context, tx pgx.Tx, p CreateHolidayOverrideParams) (models.HolidayOverride, error) {
	var h models.HolidayOverride
	err := tx.QueryRow(ctx, `
		INSERT INTO holiday_overrides (calendar_id, org_id, holiday_date, name)
		VALUES ($1, $2, $3, $4)
		RETURNING id, calendar_id, org_id, holiday_date, name, created_at`,
		p.CalendarID, p.OrgID, p.HolidayDate, p.Name,
	).Scan(&h.ID, &h.CalendarID, &h.OrgID, &h.HolidayDate, &h.Name, &h.CreatedAt)
	if err != nil {
		return models.HolidayOverride{}, fmt.Errorf("insert holiday override: %w", err)
	}
	return h, nil
}

// ListHolidaysForCalendar returns the holidays for a calendar, ordered
// by holiday_date ASC.
func (s *SetupStore) ListHolidaysForCalendar(ctx context.Context, tx pgx.Tx, calendarID uuid.UUID) ([]models.HolidayOverride, error) {
	rows, err := tx.Query(ctx, `
		SELECT id, calendar_id, org_id, holiday_date, name, created_at
		FROM holiday_overrides
		WHERE calendar_id = $1
		ORDER BY holiday_date ASC`, calendarID)
	if err != nil {
		return nil, fmt.Errorf("list holiday overrides: %w", err)
	}
	defer rows.Close()

	var out []models.HolidayOverride
	for rows.Next() {
		var h models.HolidayOverride
		if err := rows.Scan(&h.ID, &h.CalendarID, &h.OrgID, &h.HolidayDate, &h.Name, &h.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan holiday override: %w", err)
		}
		out = append(out, h)
	}
	return out, rows.Err()
}

// ---------- permit_jurisdictions ----------

// CreatePermitJurisdictionParams is the input for inserting a permit
// jurisdiction. PermitTypes and InspectionChecklist are raw JSONB
// (passed through without re-marshaling); empty slices land as
// '[]'::jsonb via the schema default.
type CreatePermitJurisdictionParams struct {
	OrgID               uuid.UUID
	Name                string
	Region              *string
	PermitTypes         []byte // raw JSONB; pass nil for the schema default
	InspectionChecklist []byte // raw JSONB; pass nil for the schema default
	Notes               *string
}

// CreatePermitJurisdiction inserts a row.
func (s *SetupStore) CreatePermitJurisdiction(ctx context.Context, tx pgx.Tx, p CreatePermitJurisdictionParams) (models.PermitJurisdiction, error) {
	// When the caller passes nil for the JSONB columns, fall back to
	// '[]' so the SQL parameter type is unambiguous (pgx infers []byte
	// = JSONB; nil bytes = NULL which the NOT NULL column rejects).
	permitTypes := p.PermitTypes
	if permitTypes == nil {
		permitTypes = []byte("[]")
	}
	checklist := p.InspectionChecklist
	if checklist == nil {
		checklist = []byte("[]")
	}

	var j models.PermitJurisdiction
	err := tx.QueryRow(ctx, `
		INSERT INTO permit_jurisdictions (org_id, name, region, permit_types, inspection_checklist, notes)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, org_id, name, region, permit_types, inspection_checklist, notes, created_at, updated_at`,
		p.OrgID, p.Name, p.Region, permitTypes, checklist, p.Notes,
	).Scan(&j.ID, &j.OrgID, &j.Name, &j.Region, &j.PermitTypes, &j.InspectionChecklist, &j.Notes, &j.CreatedAt, &j.UpdatedAt)
	if err != nil {
		return models.PermitJurisdiction{}, fmt.Errorf("insert permit jurisdiction: %w", err)
	}
	return j, nil
}

// ListPermitJurisdictions returns all permit jurisdictions for an org,
// ordered by name ASC.
func (s *SetupStore) ListPermitJurisdictions(ctx context.Context, tx pgx.Tx, orgID uuid.UUID) ([]models.PermitJurisdiction, error) {
	rows, err := tx.Query(ctx, `
		SELECT id, org_id, name, region, permit_types, inspection_checklist, notes, created_at, updated_at
		FROM permit_jurisdictions
		WHERE org_id = $1
		ORDER BY name ASC`, orgID)
	if err != nil {
		return nil, fmt.Errorf("list permit jurisdictions: %w", err)
	}
	defer rows.Close()

	var out []models.PermitJurisdiction
	for rows.Next() {
		var j models.PermitJurisdiction
		if err := rows.Scan(&j.ID, &j.OrgID, &j.Name, &j.Region, &j.PermitTypes, &j.InspectionChecklist, &j.Notes, &j.CreatedAt, &j.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan permit jurisdiction: %w", err)
		}
		out = append(out, j)
	}
	return out, rows.Err()
}
